misc: mediatek: wlan: annotate unused variable 'chip_id'
../drivers/misc/mediatek/connectivity/wlan/core/gen4m/common/wlan_lib.c:3432:11: error: unused variable 'chip_id' [-Werror,-Wunused-variable]
 3432 |         uint32_t chip_id = prChipInfo->chip_id;
      |                  ^~~~~~~
  CC      drivers/misc/mediatek/imgsensor/src/mt6768/../common/v1/ov8856_aac_front_i_mipi_raw/ov8856_aac_front_imipiraw_Sensor.o
  AR      drivers/misc/mediatek/leds/mt6768/built-in.a
  CC      drivers/misc/mediatek/eccci/port/port_cfg.o
1 error generated.

Signed-off-by: Joel Gómez <nahuelgomez329@gmail.com>